name: chat
version: 0.0.1
author: Loi Nguyen <loint@penlook.com>
description: Socket Example
environment:
    sdk: '>=1.0.0 <2.0.0'
dependencies:
    shadow_dom: any
    socket:
      path: ../client/
dev_dependencies:
    browser: any
    unittest: any
