language:
    - dart
    - go

with_content_shell: true

install:
    - . ./travis.sh
    - go get -v ./...
    - go get github.com/stretchr/testify/assert
    - (cd ./client/dart && pub get && pub global activate test_runner)

script:
    - go test
    - (cd ./pollserver && go run socket.go &)
    - (cd ./client/dart && xvfb-run -s '-screen 0 1024x768x24' pub global run test_runner --verbose --disable-ansi)