language: go

go:
  - 1.3
  - 1.4

install:
  - go get -v ./...
  - go get github.com/stretchr/testify/assert
  - (cd server; go build; sudo ./server install; sudo ./server start)
  - sudo netstat -tulpn