language:
    - dart
    - go

with_content_shell: true

install:
    - export GOPATH=$HOME/gopath:
    - export PATH=$HOME/gopath/bin:$PATH
    - mkdir -p $HOME/gopath/src/github.com/penlook/socket
    - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/penlook/socket/
    - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/penlook/socket
    - cd $HOME/gopath/src/github.com/penlook/socket
    - go get -v ./...
    - go get github.com/stretchr/testify/assert

script:
    - go test