language:
	- go
	- dart

dart:
    - stable

go:
  - 1.4

with_content_shell: true

install:
  - go get -v ./...
  - go get github.com/stretchr/testify/assert
  - (cd server; go build; sudo ./server install; sudo ./server start)
  - sudo netstat -tulpn